
use crate::lexer::{constants::Pos, token::token::TokenKind};
use std::collections::VecDeque;

/// The maximum amount of steps to store.
pub(crate) const MAX_TRACE_LEN: usize = 1024;

/// An Error generated by the Lexer
pub(crate) struct Error {
    pub(crate) chr: char,
    pub(crate) pos: Pos,
    /// The last MAX_TRACE_LEN steps done by the Lexer.
    pub(crate) traceback: VecDeque<Step>,
    /// Max number of steps to display.
    pub(crate) depth: usize
}

/// A single step done by the Lexer. (Eg. Constructing an Integer Token)
pub(crate) struct Step {
    token: TokenKind,
    /// The position where the step was done. [line, column, char]
    pos: Pos
}
